apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customer-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
      - image: amela/customers
        name: customers
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-customers:5432/customer
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
